### PR TITLE
fix empty crosswalk NCI references

### PR DESCRIPTION
**Pull request by sheridancbio**
also parameterize oncotree topbraid namespace and graph id strings

### CODE REVIEW

**Review by averyniceday — CHANGES_REQUESTED** [review]
code looks good to me!  just need to update the sample application properties file and also put in default values for the injected params :)

**Comment by averyniceday** [comment]
also looks like integration tests failed

**Comment by sheridancbio** [comment]
application.properties.EXAMPLE updated with new properties and default values have been specified in @Value annotations.
Integration tests are now passing.

**Review by averyniceday — COMMENTED** [review]
lgtm

**Pull request merged**
