### PR TITLE
Adding NCI and UMLS mappings

### PR DESCRIPTION
**Pull request by ihuerga**
Hi Oncotree team,

This is Iker Huerga from MSK (Information Systems).

I had to generate mappings between oncotree, NCI thesaurus and UMLS as part of a project I was working on. I just finished and thought this might be useful for you guys as well. 

This pull requests contains the followings additions

- Two extra columns (nci, umls) to the tumor_tree.txt file; and the corresponding CUI (Concept Unique Identifier) for each of the controlled vocabularies.

- Changes into tree.js to populate the links into the 'qtip' element. Thus, everytime the user mouse hover a node in the tree there are two new elements (NCI, UMLS) added into the pop-up. Each of them contain a clickable link to the corresponding controlled vocabulary

- A file called tumor_tree.rdf. This is an RDF (Resource Description Framework) representation of oncotree taxonomy as well as all the mappings to NCI and UMLS.

Please don't hesitate to reach out in case you have any questions, or need some clarification, my MSK email is huergasi@mskcc.org

Hope you find this useful
Iker

P.S: I added the jetty plugin to the pom.xml to make it easier to debug in your local machine. If you are using maven just run the following command from your favorite IDE or command line

mvn -Djetty.http.port=9999 jetty:run

### CODE REVIEW

**Comment by ihuerga** [comment]
Forgor to mention that I manually reviewed all the mappings one by one

**Comment by zhx828** [comment]
@ihuerga Thank you so much for doing this. I think the tumor type text file has been updated and we need to update your pull request as well. Since this is ongoing project, the text file will be change in the future, how should we keep updating all NCI and UMLS?

**Comment by ihuerga** [comment]
There are two options I can see moving forward to update the mappings

1- I'd be happy to take care of updating the mappings everytime the tumor
tree changes. I will simply make a pull request with the updated mappings
after every update to the tumor tree

2- We can set up a collaborative ontology development/management tool, such
as web protege. I'd be happy to set it up in one of our VMs. There we can
do version control on the tumor tree and their corresponding mappings.

I personally think option 1) is more short term (I can start doing that
right away if you guys are ok with it), whereas option 2) is more longer
term

Let me know your thoughts

Thanks
Iker
ᐧ

2015-11-30 12:20 GMT-05:00 HongxinZ <notifications@github.com>:

> @ihuerga <https://github.com/ihuerga> Thank you so much for doing this. I
> think the tumor type text file has been updated and we need to update your
> pull request as well. Since this is ongoing project, the text file will be
> change in the future, how should we keep updating all NCI and UMLS?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cBioPortal/oncotree/pull/7#issuecomment-160694731>.
>



-- 
Iker Huerga
http://www.ikerhuerga.com/

**Comment by zhx828** [comment]
@ihuerga Any updates on this pull request?

**Pull request closed without merging**
